### ISSUE TITLE
error checking archive file

### ISSUE THREAD

**Issue by Coloradohusky** [jjjake/internetarchive#408]
I'm trying to upload a 7zip file in parts, due to it being 100gb total, but internetarchive doesn't like that.
```
 error uploading wigglesfandomcom-20210525-wikidump.7z.001: Uploaded content is unacceptable. - error checking archive file
Traceback (most recent call last):
  File "C:\Users\Coloradohusky\AppData\Local\Programs\Python\Python38\lib\site-packages\internetarchive\item.py", line 1080, in upload_file
    response.raise_for_status()
  File "C:\Users\Coloradohusky\AppData\Local\Programs\Python\Python38\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Data for url: https://s3.us.archive.org/wigglesfandomcom-20210525-wikidump/wigglesfandomcom-20210525-wikidump.7z.001

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Coloradohusky\Desktop\upload_wikis.py", line 35, in <module>
    uploadWebsites('E')
  File "C:\Users\Coloradohusky\Desktop\upload_wikis.py", line 27, in uploadWebsites
    item.upload('./' + website + '.7z.' + ("%03d"%i), metadata=meta, checksum=True, delete=True, verbose=True)
  File "C:\Users\Coloradohusky\AppData\Local\Programs\Python\Python38\lib\site-packages\internetarchive\item.py", line 1249, in upload
    resp = self.upload_file(body,
  File "C:\Users\Coloradohusky\AppData\Local\Programs\Python\Python38\lib\site-packages\internetarchive\item.py", line 1106, in upload_file
    raise type(exc)(error_msg, response=exc.response, request=exc.request)
requests.exceptions.HTTPError:  error uploading wigglesfandomcom-20210525-wikidump.7z.001 to wigglesfandomcom-20210525-wikidump, Uploaded content is unacceptable. - error checking archive file
```

**Comment by jjjake** [comment]
Are you able to point me to a copy of the file so I can try to replicate? I have a feeling it might be something to do with your extension.

**Comment by Coloradohusky** [comment]
Sorry, I should’ve provided more context - I used the https://documentation.help/7-Zip/volume.htm flag with 7z, which splits the archive into different pieces, but each piece isn’t extractable on its own, it can only be extracted as a whole - so what’s happening is Archive is trying to unzip the .7z.001 file, but can’t since it’s not a complete archive

**Comment by jjjake** [comment]
I confirmed that this is a bug in our S3-like API. We have code that verifies a files contents matches it's extension (e.g. it's not a movie with a `.jpg` extension).

It looks like we are seeing this is a 7z file, but it doesn't pass our verification even though it's valid. I think we should be able to fix this without much trouble. I'll keep you posted. Thanks for the report!

**Comment by jjjake** [comment]
Ok, the bug has been patched and we're pushing it out now. It'll take a bit of time before it's completely pushed out, but it should be fixed soon (I would guess most definitely by tomorrow, probably a lot sooner).

**Comment by MAVProxyUser** [comment]
I'm still seeing this today for what it is worth, with a .z01 file.

**Comment by akbaryahya** [comment]
I have the same problem only `.z01` is not uploaded successfully, other parts are fine, what is the solution?

**Comment by MAVProxyUser** [comment]
gzip the .z01 and call it a day.
